# **AI And Biotechnology/Bioinformatics**

## **AI and Drug Discovery Course: QSAR Modeling**
This notebook demonstrates how to collect and preprocess bioactivity data from ChEMBL for QSAR modeling

# **Part 1: Data Collection & Curation**

**First we need to connect Google Colab with our Google Drive, so that we can have access to our Google drive within Colab.**

This allows us to:
* Save datasets
* Reload data across sessions
* Organize project files

In [2]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

**Now create "data" folder in our "Colab Notebooks" folder on Google Drive.**

In [3]:
! mkdir "/content/gdrive/My Drive/Colab Notebooks/data"

## Install and Import Required Libraries
We install the ChEMBL web service package so that we can retrieve bioactivity data

In [4]:
!pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.2.1-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.1.4)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (25.4.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-25.3.0-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.5.1)
Collecting url-normalize>=1.4 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-2.2.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 1.8 MB/s eta 0:00:00
Downloading requests_cache-1.2.1-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.4/61.4 kB 4.4 MB/s eta 0:00:00
Downloading cattrs-25.3.0-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.7/70.7 kB 5.0 MB/s eta 0:00:00
Downloading url_normalize-2.2.1-py3-none-any.whl (14 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-25.3.0 chembl_webresource_client-0.10.9 requests-cache-1.2.1 url-normalize-2.2.1

# Import Libraries
* pandas for data handling
* new_client from chembl for accessing the database

In [5]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

# Step 1: Search for Traget Protein

## **Target Identification (KRAS)**
Search ChEMBL for the KRAS target and select the most relevant entry.

In [6]:
target = new_client.target
target_query = target.search("PI3-kinase class I")
targets = pd.DataFrame.from_dict(target_query)
targets.head()

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,PI3-kinase class I,35.0,False,CHEMBL3559703,"[{'accession': 'P27986', 'component_descriptio...",PROTEIN COMPLEX GROUP,9606.0
1,[],Homo sapiens,VPS15-VPS34,23.0,False,CHEMBL5483084,"[{'accession': 'Q8NEB9', 'component_descriptio...",PROTEIN COMPLEX,9606.0
2,[],Rattus norvegicus,Phosphatidylinositol 3-kinase catalytic subuni...,22.0,False,CHEMBL5291577,"[{'accession': 'O88763', 'component_descriptio...",SINGLE PROTEIN,10116.0
3,[],Homo sapiens,Phosphatidylinositol 3-kinase catalytic subuni...,20.0,False,CHEMBL1075165,"[{'accession': 'Q8NEB9', 'component_descriptio...",SINGLE PROTEIN,9606.0
4,[],Homo sapiens,Phosphoinositide 3-kinase regulatory subunit 4,19.0,False,CHEMBL2189144,"[{'accession': 'Q99570', 'component_descriptio...",SINGLE PROTEIN,9606.0

**Reterive Bioactivity data for selected target**

In [7]:
selected_target = targets.target_chembl_id[0]
selected_target

'CHEMBL3559703'

**Now retrieve only bioactivity data for target; **GTPase KRas(CHEMBL2189121)** with reported IC 50  values in nM (nanomolar) unit.**

In [8]:
activity = new_client.activity
results = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [9]:
df1 = pd.DataFrame.from_dict(results)
df1.head(5)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,313562,17693762,[],CHEMBL3706369,Binding Assay: The efficacy of compounds of th...,B,None,None,BAO_0000190,...,Homo sapiens,PI3-kinase class I,9606,None,None,IC50,nM,UO_0000065,None,459.0
1,None,313563,17693763,[],CHEMBL3706369,Binding Assay: The efficacy of compounds of th...,B,None,None,BAO_0000190,...,Homo sapiens,PI3-kinase class I,9606,None,None,IC50,nM,UO_0000065,None,1730.0
2,None,313564,17693764,[],CHEMBL3706369,Binding Assay: The efficacy of compounds of th...,B,None,None,BAO_0000190,...,Homo sapiens,PI3-kinase class I,9606,None,None,IC50,nM,UO_0000065,None,2881.0
3,None,313565,17693765,[],CHEMBL3706369,Binding Assay: The efficacy of compounds of th...,B,None,None,BAO_0000190,...,Homo sapiens,PI3-kinase class I,9606,None,None,IC50,nM,UO_0000065,None,422.0
4,None,313566,17693766,[],CHEMBL3706369,Binding Assay: The efficacy of compounds of th...,B,None,None,BAO_0000190,...,Homo sapiens,PI3-kinase class I,9606,None,None,IC50,nM,UO_0000065,None,349.0

In [10]:
df1.standard_type.unique()

array(['IC50'], dtype=object)

**Finally Save the resulting bioactivity data to a CSV file** **bioactivity_raw_data.csv**.

In [11]:
df1.to_csv('bioactivity_raw_data.csv', index=False)

**Now copy "bioactivity_raw_data.csv" file to Google Drive, in foler "data"**

In [12]:
! cp bioactivity_raw_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"

In [13]:
! ls -l "/content/gdrive/My Drive/Colab Notebooks/data"

total 583
-rw------- 1 root root 596629 Jan 26 19:21 bioactivity_raw_data.csv

In [14]:
! head bioactivity_raw_data.csv

action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,313562,17693762,[],CHEMBL3706369,"Binding Assay: The efficacy of compounds of the invention in inhibiting the PI3K induced-lipid phosphorylation may be tested in the following binding assay. The assay combines the scintillation proximity assay technology (SPA, Amersham) with the capacity of neomycin (a polycationic antibiotic) to bind phospholipids with high affinity and specificity. The Scintillation Proximity Assay is based on the properties of weakly emitting isotopes (such as 3H, 125I, 33P). Coating SPA beads with neomycin allows the detection of phosphorylated lipid substrates after incubation with recombinant PI3K and radioactive ATP in the same well, by capturing the radioactive phospholipids to the SPA beads through their specific binding to neomycin. To a 384 wells MTP containing 5 ul of the test compound of Formula (I) (solubilized in 2% DMSO; to yield a final concentration of 20, 5, 1.25, 0.3125, 0.0781, 0.0195, 0.0049, 0.0012, 0.0003 and 0.00075 uM of the test compound).",B,,,BAO_0000190,BAO_0000223,protein complex format,COc1cccc2c1S(=O)(=O)Cc1c(C(=O)N3CCOCC3)nn(-c3ccccc3)c1-2,,,CHEMBL3639174,,2015,"{'bei': '14.42', 'le': '0.28', 'lle': '4.03', 'sei': '6.99'}",CHEMBL3678513,,CHEMBL3678513,6.34,0,http://www.openphacts.org/units/Nanomolar,2554318,=,37,1,=,,IC50,nM,,459.0,CHEMBL3559703,Homo sapiens,PI3-kinase class I,9606,,,IC50,nM,UO_0000065,,459.0
,313563,17693763,[],CHEMBL3706369,"Binding Assay: The efficacy of compounds of the invention in inhibiting the PI3K induced-lipid phosphorylation may be tested in the following binding assay. The assay combines the scintillation proximity assay technology (SPA, Amersham) with the capacity of neomycin (a polycationic antibiotic) to bind phospholipids with high affinity and specificity. The Scintillation Proximity Assay is based on the properties of weakly emitting isotopes (such as 3H, 125I, 33P). Coating SPA beads with neomycin allows the detection of phosphorylated lipid substrates after incubation with recombinant PI3K and radioactive ATP in the same well, by capturing the radioactive phospholipids to the SPA beads through their specific binding to neomycin. To a 384 wells MTP containing 5 ul of the test compound of Formula (I) (solubilized in 2% DMSO; to yield a final concentration of 20, 5, 1.25, 0.3125, 0.0781, 0.0195, 0.0049, 0.0012, 0.0003 and 0.00075 uM of the test compound).",B,,,BAO_0000190,BAO_0000223,protein complex format,COc1cccc2c1S(=O)(=O)Cc1c(C(=O)N3CCOCC3)nn(C)c1-2,,,CHEMBL3639174,,2015,"{'bei': '15.27', 'le': '0.30', 'lle': '4.90', 'sei': '6.35'}",CHEMBL3678514,,CHEMBL3678514,5.76,0,http://www.openphacts.org/units/Nanomolar,2554319,=,37,1,=,,IC50,nM,,1730.0,CHEMBL3559703,Homo sapiens,PI3-kinase class I,9606,,,IC50,nM,UO_0000065,,1730.0
,313564,17693764,[],CHEMBL3706369,"Binding Assay: The efficacy of compounds of the invention in inhibiting the PI3K induced-lipid phosphorylation may be tested in the following binding assay. The assay combines the scintillation proximity assay technology (SPA, Amersham) with the capacity of neomycin (a polycationic antibiotic) to bind phospholipids with high affinity and specificity. The Scintillation Proximity Assay is based on the properties of weakly emitting isotopes (such as 3H, 125I, 33P). Coating SPA beads with neomycin allows the detection of phosphorylated lipid substrates after incubation with recombinant PI3K and radioactive ATP in the same well, by capturing the radioactive phospholipids to the SPA beads through their specific binding to neomycin. To a 384 wells MTP containing 5 ul of the test compound of Formula (I) (solubilized in 2% DMSO; to yield a final concentration of 20, 5, 1.25, 0.3125, 0.0781, 0.0195, 0.0049, 0.0012, 0.0003 and 0.00075 uM of the test compound).",B,,,BAO_0000190,BAO_0000223,protein complex format,O=C(c1n[nH]c2c1CS(=O)(=O)c1ccccc1-2)N1CCOCC1,,,CHEMBL3639174,,2015,"{'bei': '16.62', 'le': '0.33', 'lle': '4.70', 'sei': '6.00'}",CHEMBL3678515,,CHEMBL3678515,5.54,0,http://www.openphacts.org/units/Nanomolar,2554320,=,37,1,=,,IC50,nM,,2881.0,CHEMBL3559703,Homo sapiens,PI3-kinase class I,9606,,,IC50,nM,UO_0000065,,2881.0
,313565,17693765,[],CHEMBL3706369,"Binding Assay: The efficacy of compounds of the invention in inhibiting the PI3K induced-lipid phosphorylation may be tested in the following binding assay. The assay combines the scintillation proximity assay technology (SPA, Amersham) with the capacity of neomycin (a polycationic antibiotic) to bind phospholipids with high affinity and specificity. The Scintillation Proximity Assay is based on the properties of weakly emitting isotopes (such as 3H, 125I, 33P). Coating SPA beads with neomycin allows the detection of phosphorylated lipid substrates after incubation with recombinant PI3K and radioactive ATP in the same well, by capturing the radioactive phospholipids to the SPA beads through their specific binding to neomycin. To a 384 wells MTP containing 5 ul of the test compound of Formula (I) (solubilized in 2% DMSO; to yield a final concentration of 20, 5, 1.25, 0.3125, 0.0781, 0.0195, 0.0049, 0.0012, 0.0003 and 0.00075 uM of the test compound).",B,,,BAO_0000190,BAO_0000223,protein complex format,COc1ccc2c(c1)S(=O)(=O)Cc1c(C(=O)N3CCOCC3)nn(C)c1-2,,,CHEMBL3639174,,2015,"{'bei': '16.89', 'le': '0.33', 'lle': '5.51', 'sei': '7.03'}",CHEMBL3678516,,CHEMBL3678516,6.38,0,http://www.openphacts.org/units/Nanomolar,2554321,=,37,1,=,,IC50,nM,,422.0,CHEMBL3559703,Homo sapiens,PI3-kinase class I,9606,,,IC50,nM,UO_0000065,,422.0
,313566,17693766,[],CHEMBL3706369,"Binding Assay: The efficacy of compounds of the invention in inhibiting the PI3K induced-lipid phosphorylation may be tested in the following binding assay. The assay combines the scintillation proximity assay technology (SPA, Amersham) with the capacity of neomycin (a polycationic antibiotic) to bind phospholipids with high affinity and specificity. The Scintillation Proximity Assay is based on the properties of weakly emitting isotopes (such as 3H, 125I, 33P). Coating SPA beads with neomycin allows the detection of phosphorylated lipid substrates after incubation with recombinant PI3K and radioactive ATP in the same well, by capturing the radioactive phospholipids to the SPA beads through their specific binding to neomycin. To a 384 wells MTP containing 5 ul of the test compound of Formula (I) (solubilized in 2% DMSO; to yield a final concentration of 20, 5, 1.25, 0.3125, 0.0781, 0.0195, 0.0049, 0.0012, 0.0003 and 0.00075 uM of the test compound).",B,,,BAO_0000190,BAO_0000223,protein complex format,COc1ccc2c(c1)S(=O)(=O)Cc1c(C(=O)N3CCOCC3)nn(-c3ccccc3)c1-2,,,CHEMBL3639174,,2015,"{'bei': '14.69', 'le': '0.28', 'lle': '4.15', 'sei': '7.12'}",CHEMBL3678517,,CHEMBL3678517,6.46,0,http://www.openphacts.org/units/Nanomolar,2554322,=,37,1,=,,IC50,nM,,349.0,CHEMBL3559703,Homo sapiens,PI3-kinase class I,9606,,,IC50,nM,UO_0000065,,349.0
,313567,17693767,[],CHEMBL3706369,"Binding Assay: The efficacy of compounds of the invention in inhibiting the PI3K induced-lipid phosphorylation may be tested in the following binding assay. The assay combines the scintillation proximity assay technology (SPA, Amersham) with the capacity of neomycin (a polycationic antibiotic) to bind phospholipids with high affinity and specificity. The Scintillation Proximity Assay is based on the properties of weakly emitting isotopes (such as 3H, 125I, 33P). Coating SPA beads with neomycin allows the detection of phosphorylated lipid substrates after incubation with recombinant PI3K and radioactive ATP in the same well, by capturing the radioactive phospholipids to the SPA beads through their specific binding to neomycin. To a 384 wells MTP containing 5 ul of the test compound of Formula (I) (solubilized in 2% DMSO; to yield a final concentration of 20, 5, 1.25, 0.3125, 0.0781, 0.0195, 0.0049, 0.0012, 0.0003 and 0.00075 uM of the test compound).",B,,,BAO_0000190,BAO_0000223,protein complex format,Cc1cccc(-n2nc(C(=O)N3CCOCC3)c3c2-c2ccccc2S(=O)(=O)C3)c1,,,CHEMBL3639174,,2015,"{'bei': '14.25', 'le': '0.27', 'lle': '3.42', 'sei': '7.40'}",CHEMBL3639773,,CHEMBL3639773,6.03,0,http://www.openphacts.org/units/Nanomolar,2554323,=,37,1,=,,IC50,nM,,926.0,CHEMBL3559703,Homo sapiens,PI3-kinase class I,9606,,,IC50,nM,UO_0000065,,926.0
,313568,17693768,[],CHEMBL3706369,"Binding Assay: The efficacy of compounds of the invention in inhibiting the PI3K induced-lipid phosphorylation may be tested in the following binding assay. The assay combines the scintillation proximity assay technology (SPA, Amersham) with the capacity of neomycin (a polycationic antibiotic) to bind phospholipids with high affinity and specificity. The Scintillation Proximity Assay is based on the properties of weakly emitting isotopes (such as 3H, 125I, 33P). Coating SPA beads with neomycin allows the detection of phosphorylated lipid substrates after incubation with recombinant PI3K and radioactive ATP in the same well, by capturing the radioactive phospholipids to the SPA beads through their specific binding to neomycin. To a 384 wells MTP containing 5 ul of the test compound of Formula (I) (solubilized in 2% DMSO; to yield a final concentration of 20, 5, 1.25, 0.3125, 0.0781, 0.0195, 0.0049, 0.0012, 0.0003 and 0.00075 uM of the test compound).",B,,,BAO_0000190,BAO_0000223,protein complex format,Cc1ccc(-n2nc(C(=O)N3CCOCC3)c3c2-c2ccccc2S(=O)(=O)C3)cc1,,,CHEMBL3639174,,2015,"{'bei': '14.55', 'le': '0.28', 'lle': '3.55', 'sei': '7.56'}",CHEMBL3678518,,CHEMBL3678518,6.16,0,http://www.openphacts.org/units/Nanomolar,2554324,=,37,1,=,,IC50,nM,,690.0,CHEMBL3559703,Homo sapiens,PI3-kinase class I,9606,,,IC50,nM,UO_0000065,,690.0
,313569,17693769,[],CHEMBL3706369,"Binding Assay: The efficacy of compounds of the invention in inhibiting the PI3K induced-lipid phosphorylation may be tested in the following binding assay. The assay combines the scintillation proximity assay technology (SPA, Amersham) with the capacity of neomycin (a polycationic antibiotic) to bind phospholipids with high affinity and specificity. The Scintillation Proximity Assay is based on the properties of weakly emitting isotopes (such as 3H, 125I, 33P). Coating SPA beads with neomycin allows the detection of phosphorylated lipid substrates after incubation with recombinant PI3K and radioactive ATP in the same well, by capturing the radioactive phospholipids to the SPA beads through their specific binding to neomycin. To a 384 wells MTP containing 5 ul of the test compound of Formula (I) (solubilized in 2% DMSO; to yield a final concentration of 20, 5, 1.25, 0.3125, 0.0781, 0.0195, 0.0049, 0.0012, 0.0003 and 0.00075 uM of the test compound).",B,,,BAO_0000190,BAO_0000223,protein complex format,Cc1ccc(F)cc1-n1nc(C(=O)N2CCOCC2)c2c1-c1ccccc1S(=O)(=O)C2,,,CHEMBL3639174,,2015,"{'bei': '12.18', 'le': '0.24', 'lle': '2.63', 'sei': '6.60'}",CHEMBL3678519,,CHEMBL3678519,5.38,0,http://www.openphacts.org/units/Nanomolar,2554325,=,37,1,=,,IC50,nM,,4195.0,CHEMBL3559703,Homo sapiens,PI3-kinase class I,9606,,,IC50,nM,UO_0000065,,4195.0
,313570,17693770,[],CHEMBL3706369,"Binding Assay: The efficacy of compounds of the invention in inhibiting the PI3K induced-lipid phosphorylation may be tested in the following binding assay. The assay combines the scintillation proximity assay technology (SPA, Amersham) with the capacity of neomycin (a polycationic antibiotic) to bind phospholipids with high affinity and specificity. The Scintillation Proximity Assay is based on the properties of weakly emitting isotopes (such as 3H, 125I, 33P). Coating SPA beads with neomycin allows the detection of phosphorylated lipid substrates after incubation with recombinant PI3K and radioactive ATP in the same well, by capturing the radioactive phospholipids to the SPA beads through their specific binding to neomycin. To a 384 wells MTP containing 5 ul of the test compound of Formula (I) (solubilized in 2% DMSO; to yield a final concentration of 20, 5, 1.25, 0.3125, 0.0781, 0.0195, 0.0049, 0.0012, 0.0003 and 0.00075 uM of the test compound).",B,,,BAO_0000190,BAO_0000223,protein complex format,COc1cccc(-n2nc(C(=O)N3CCOCC3)c3c2-c2ccccc2S(=O)(=O)C3)c1,,,CHEMBL3639174,,2015,"{'bei': '13.38', 'le': '0.26', 'lle': '3.57', 'sei': '6.48'}",CHEMBL3678520,,CHEMBL3678520,5.88,0,http://www.openphacts.org/units/Nanomolar,2554326,=,37,1,=,,IC50,nM,,1320.0,CHEMBL3559703,Homo sapiens,PI3-kinase class I,9606,,,IC50,nM,UO_0000065,,1320.0

# **Step 3: Bioactivity Data Retrieval (IC50)**
**Retrieve bioactivity data (IC50) for the selected KRAS target.**

**Inspect Missing Values**

In [15]:
df1["standard_type"].isna().sum()

np.int64(0)

**Filter Rows with Valid Bioactivity Values**

In [18]:
df2 = df1[df1["standard_value"].notna()]
df2.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,313562,17693762,[],CHEMBL3706369,Binding Assay: The efficacy of compounds of th...,B,None,None,BAO_0000190,...,Homo sapiens,PI3-kinase class I,9606,None,None,IC50,nM,UO_0000065,None,459.0
1,None,313563,17693763,[],CHEMBL3706369,Binding Assay: The efficacy of compounds of th...,B,None,None,BAO_0000190,...,Homo sapiens,PI3-kinase class I,9606,None,None,IC50,nM,UO_0000065,None,1730.0
2,None,313564,17693764,[],CHEMBL3706369,Binding Assay: The efficacy of compounds of th...,B,None,None,BAO_0000190,...,Homo sapiens,PI3-kinase class I,9606,None,None,IC50,nM,UO_0000065,None,2881.0
3,None,313565,17693765,[],CHEMBL3706369,Binding Assay: The efficacy of compounds of th...,B,None,None,BAO_0000190,...,Homo sapiens,PI3-kinase class I,9606,None,None,IC50,nM,UO_0000065,None,422.0
4,None,313566,17693766,[],CHEMBL3706369,Binding Assay: The efficacy of compounds of th...,B,None,None,BAO_0000190,...,Homo sapiens,PI3-kinase class I,9606,None,None,IC50,nM,UO_0000065,None,349.0

**Assign Bioactivity Classes**
Define active, intermediate, and inactive classes based on IC50 values.

In [19]:
bioactivity_class = []
for value in df2.standard_value:
    value = float(value)
    if value >= 10000:
        bioactivity_class.append("inactive")
    elif value <= 1000:
        bioactivity_class.append("active")
    else:
        bioactivity_class.append("intermediate")

**Extract Relevant Columns**

In [20]:
molecule_ids = df2.molecule_chembl_id.tolist()
canonical_smiles = df2.canonical_smiles.tolist()
standard_values = df2.standard_value.tolist()

In [21]:
data = list(zip(
    molecule_ids,
    canonical_smiles,
    standard_values,
        bioactivity_class,
))

**Create Preprocessed bioactivity Dataset**

In [22]:

df3 = pd.DataFrame(
    data,
    columns=[
        "molecule_chembl_id",
        "canonical_smiles",
        "standard_value",
        "bioactivity_class",
    ]
)
df3.head()

,molecule_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL3678513,COc1cccc2c1S(=O)(=O)Cc1c(C(=O)N3CCOCC3)nn(-c3c...,459.0,active
1,CHEMBL3678514,COc1cccc2c1S(=O)(=O)Cc1c(C(=O)N3CCOCC3)nn(C)c1-2,1730.0,intermediate
2,CHEMBL3678515,O=C(c1n[nH]c2c1CS(=O)(=O)c1ccccc1-2)N1CCOCC1,2881.0,intermediate
3,CHEMBL3678516,COc1ccc2c(c1)S(=O)(=O)Cc1c(C(=O)N3CCOCC3)nn(C)...,422.0,active
4,CHEMBL3678517,COc1ccc2c(c1)S(=O)(=O)Cc1c(C(=O)N3CCOCC3)nn(-c...,349.0,active

**Remove Compounds without Valid SMILES**. Drop rows with **NaN**, **empty** or **None** SMILES values.

In [23]:
df3 = df3.dropna(subset=["canonical_smiles"])
df3 = df3[df3["canonical_smiles"].str.lower() != "none"]
df3 = df3[df3["canonical_smiles"].str.strip() != ""]
df3.head()

,molecule_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL3678513,COc1cccc2c1S(=O)(=O)Cc1c(C(=O)N3CCOCC3)nn(-c3c...,459.0,active
1,CHEMBL3678514,COc1cccc2c1S(=O)(=O)Cc1c(C(=O)N3CCOCC3)nn(C)c1-2,1730.0,intermediate
2,CHEMBL3678515,O=C(c1n[nH]c2c1CS(=O)(=O)c1ccccc1-2)N1CCOCC1,2881.0,intermediate
3,CHEMBL3678516,COc1ccc2c(c1)S(=O)(=O)Cc1c(C(=O)N3CCOCC3)nn(C)...,422.0,active
4,CHEMBL3678517,COc1ccc2c(c1)S(=O)(=O)Cc1c(C(=O)N3CCOCC3)nn(-c...,349.0,active

**Save Preprocessed Bioactivity Data.** Save the cleaned dataset to CSV and copy to Google Drive.

In [24]:
df3.to_csv("bioactivity_preprocessed_data.csv", index=False)

!cp bioactivity_preprocessed_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"
!ls "/content/gdrive/My Drive/Colab Notebooks/data"

bioactivity_preprocessed_data.csv  bioactivity_raw_data.csv

## **End of Part 1: Data Collection and Curation**