## **AI And Biotechnology/Bioinformatics**

## **AI and Drug Discovery Course: QSAR Modeling**
This notebook demonstrates how to collect and preprocess bioactivity data from ChEMBL for QSAR modeling

# **Part 3: Descriptor Calculation**

PaDELPy is a Python wrapper for the PaDEL-Descriptor (molecular descriptor calculation) software.  

It provide the following descriptors/fingerprint:  
* 1444 - 2D Descriptors
* 431 - 3D Descriptors
* 881 bits - PubChem Fingerprints

## **Install PaDELpy**

In [1]:
!pip install padelpy

Collecting padelpy
  Downloading padelpy-0.1.16-py3-none-any.whl.metadata (7.7 kB)
Downloading padelpy-0.1.16-py3-none-any.whl (20.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.9/20.9 MB 62.0 MB/s eta 0:00:00
Installing collected packages: padelpy
Successfully installed padelpy-0.1.16

## **Import libraries**

In [2]:
import pandas as pd
import numpy as np
from google.colab import files
from padelpy import padeldescriptor

## **Load dataset**

In [3]:
from google.colab import files

uploaded = files.upload()

Saving df_lipinski.csv to df_lipinski.csv

In [4]:
df = pd.read_csv('df_lipinski.csv')
df.head()

,molecule_chembl_id,bioactivity_class,pIC50,canonical_smiles,MW,LogP,NumHDonors,NumHAcceptors
0,CHEMBL3639825,active,6.978811,CC(=O)NCCN1CCC[C@H](n2nc(C(=O)N3CCOCC3)c3c2-c2...,501.609,1.0828,1.0,7.0
1,CHEMBL3678595,active,6.057496,CC(=O)Nc1ccc2c(c1)-c1c(c(C(=O)N3CCOCC3)nn1-c1c...,466.519,2.2574,1.0,6.0
2,CHEMBL3683539,active,6.546682,CC(=O)Nc1nc2c(s1)S(=O)(=O)Cc1c(C(=O)N3CCOCC3)n...,481.556,1.0762,1.0,9.0
3,CHEMBL3683549,active,6.059982,CC(=O)OCCN1CCC(n2nc(C(=O)N3CCOCC3)c3c2-c2ccccc...,488.566,1.1197,0.0,8.0
4,CHEMBL3678705,active,6.231362,CC(C)(C)CCN1CCCC(n2nc(C(=O)N3CCOCC3)c3c2-c2ccc...,500.665,3.3829,0.0,6.0

In [5]:
data = df[['canonical_smiles', 'molecule_chembl_id']]
data.head()

                                    canonical_smiles molecule_chembl_id
0  CC(=O)NCCN1CCC[C@H](n2nc(C(=O)N3CCOCC3)c3c2-c2...      CHEMBL3639825
1  CC(=O)Nc1ccc2c(c1)-c1c(c(C(=O)N3CCOCC3)nn1-c1c...      CHEMBL3678595
2  CC(=O)Nc1nc2c(s1)S(=O)(=O)Cc1c(C(=O)N3CCOCC3)n...      CHEMBL3683539
3  CC(=O)OCCN1CCC(n2nc(C(=O)N3CCOCC3)c3c2-c2ccccc...      CHEMBL3683549
4  CC(C)(C)CCN1CCCC(n2nc(C(=O)N3CCOCC3)c3c2-c2ccc...      CHEMBL3678705

## **Convert to .smi format**

In [6]:
df_smi = data['canonical_smiles'].to_csv('smiles_chembl.smi', index=None, header=None)

In [7]:
! cat smiles_chembl.smi | head

CC(=O)NCCN1CCC[C@H](n2nc(C(=O)N3CCOCC3)c3c2-c2ccccc2S(=O)(=O)C3)C1
CC(=O)Nc1ccc2c(c1)-c1c(c(C(=O)N3CCOCC3)nn1-c1ccccc1)CS2(=O)=O
CC(=O)Nc1nc2c(s1)S(=O)(=O)Cc1c(C(=O)N3CCOCC3)nn(C3CCOCC3)c1-2
CC(=O)OCCN1CCC(n2nc(C(=O)N3CCOCC3)c3c2-c2ccccc2S(=O)(=O)C3)C1
CC(C)(C)CCN1CCCC(n2nc(C(=O)N3CCOCC3)c3c2-c2ccccc2S(=O)(=O)C3)C1
CC(C)(C)OC(=O)N1CCC(Cn2nc(C(=O)N3CCOCC3)c3c2-c2ccccc2S(=O)(=O)C3)CC1
CC(C)(C)OC(=O)N1CCC(n2nc(C(=O)N3CCOCC3)c3c2-c2ccccc2S(=O)(=O)C3)CC1
CC(C)(C)OC(=O)N1CCCC(n2nc(C(=O)N3CCOCC3)c3c2-c2ccccc2S(=O)(=O)C3)CC1
CC(C)(CN1CCOCC1)c1ccc(-n2nc(C(=O)N3CCOCC3)c3c2-c2ccccc2S(=O)(=O)C3)cc1
CC(C)(c1ccc(-n2nc(C(=O)N3CCOCC3)c3c2-c2ccccc2S(=O)(=O)C3)cc1)N1CCOCC1

## **Calculate molecular Pubchem Fingerprints using "padeldescriptor" function**

In [8]:
padeldescriptor(mol_dir= "smiles_chembl.smi",
                d_file='pubchem_fingerprints.csv',
                fingerprints = True,
                retainorder= True,
                #removesalt = True, standardizetautomers = True, standardizenitro=True
                )

In [9]:
!ls -lh pubchem_fingerprints.csv

-rw-r--r-- 1 root root 531K Feb 22 19:23 pubchem_fingerprints.csv

In [10]:
df_fingerprint = pd.read_csv("pubchem_fingerprints.csv")
df_fingerprint.head()

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,AUTOGEN_smiles_chembl_1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,AUTOGEN_smiles_chembl_2,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,AUTOGEN_smiles_chembl_3,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,AUTOGEN_smiles_chembl_4,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,AUTOGEN_smiles_chembl_5,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## **Prepare Dataset for ML**

In [11]:
df.head()

,molecule_chembl_id,bioactivity_class,pIC50,canonical_smiles,MW,LogP,NumHDonors,NumHAcceptors
0,CHEMBL3639825,active,6.978811,CC(=O)NCCN1CCC[C@H](n2nc(C(=O)N3CCOCC3)c3c2-c2...,501.609,1.0828,1.0,7.0
1,CHEMBL3678595,active,6.057496,CC(=O)Nc1ccc2c(c1)-c1c(c(C(=O)N3CCOCC3)nn1-c1c...,466.519,2.2574,1.0,6.0
2,CHEMBL3683539,active,6.546682,CC(=O)Nc1nc2c(s1)S(=O)(=O)Cc1c(C(=O)N3CCOCC3)n...,481.556,1.0762,1.0,9.0
3,CHEMBL3683549,active,6.059982,CC(=O)OCCN1CCC(n2nc(C(=O)N3CCOCC3)c3c2-c2ccccc...,488.566,1.1197,0.0,8.0
4,CHEMBL3678705,active,6.231362,CC(C)(C)CCN1CCCC(n2nc(C(=O)N3CCOCC3)c3c2-c2ccc...,500.665,3.3829,0.0,6.0

In [12]:
# Select only the columns we need for ML
meta_cols = df[['molecule_chembl_id', 'bioactivity_class', 'pIC50']]

# Reset index to ensure proper alignment
meta_cols = meta_cols.reset_index(drop=True)
df_fingerprint = df_fingerprint.reset_index(drop=True)

# Combine meta data with fingerprints
combined_df = pd.concat([meta_cols, df_fingerprint.drop(df_fingerprint.columns[0], axis=1)], axis=1)

# Inspect the first few rows
combined_df.head()

,molecule_chembl_id,bioactivity_class,pIC50,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL3639825,active,6.978811,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL3678595,active,6.057496,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CHEMBL3683539,active,6.546682,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL3683549,active,6.059982,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL3678705,active,6.231362,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## **Save and download the dataset**

In [13]:
# Save as CSV
combined_df.to_csv("QSAR_dataset.csv", index=False)
print("Combined dataset saved as QSAR_dataset.csv")

# Download file in Colab
files.download("QSAR_dataset.csv")

Combined dataset saved as QSAR_dataset.csv

# **Calculate other fingerprints**

## **Download xml Files from Github**

In [14]:
!wget https://github.com/AI-Biotechnology-Bioinformatics/Drug_Discovery_AI_Course_2026/raw/main/padel_descriptors_xml.zip

--2026-02-22 19:24:17--  https://github.com/AI-Biotechnology-Bioinformatics/Drug_Discovery_AI_Course_2026/raw/main/padel_descriptors_xml.zip
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/AI-Biotechnology-Bioinformatics/Drug_Discovery_AI_Course_2026/main/padel_descriptors_xml.zip [following]
--2026-02-22 19:24:17--  https://raw.githubusercontent.com/AI-Biotechnology-Bioinformatics/Drug_Discovery_AI_Course_2026/main/padel_descriptors_xml.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10871 (11K) [application/zip]
Saving to: ‘padel_descriptors_xml.zip’

padel_descriptors_x 100%[===================>]  10.62K  --.-KB/s    in 0s

2026-02-22 19:24:17 (26.6 MB/s) - ‘padel_descriptors_xml.zip’ saved [10871/10871]

## **Unzip all files**

In [15]:
!unzip padel_descriptors_xml.zip

Archive:  padel_descriptors_xml.zip
  inflating: AtomPairs2DFingerprintCount.xml
  inflating: AtomPairs2DFingerprinter.xml
  inflating: EStateFingerprinter.xml
  inflating: ExtendedFingerprinter.xml
  inflating: Fingerprinter.xml
  inflating: GraphOnlyFingerprinter.xml
  inflating: KlekotaRothFingerprintCount.xml
  inflating: KlekotaRothFingerprinter.xml
  inflating: MACCSFingerprinter.xml
  inflating: PubchemFingerprinter.xml
  inflating: SubstructureFingerprintCount.xml
  inflating: SubstructureFingerprinter.xml

## **Calculate Fingerprints**

In [16]:
# Specify the XML file for SubstructureFingerprinter directly
Substruc_fp = "SubstructureFingerprinter.xml"

# Calculate Substructure fingerprints
padeldescriptor(
    mol_dir='smiles_chembl.smi',
    d_file='Substructure_fingerprints.csv',
    fingerprints=True,
    descriptortypes= Substruc_fp,
    retainorder=True
    # removesalt=True, standardizetautomers=True
)